apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/guilhermefaleiros/argocd.git"
    targetRevision: HEAD
    path: kustomize
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kustomize
