apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: "https://prometheus-community.github.io/helm-charts"
      chart: prometheus
      targetRevision: 25.30.1
      helm:
        releaseName: prometheus
        valueFiles:
          - $values/prometheus/values.yaml
    - repoURL: "https://github.com/guilhermefaleiros/argocd.git"
      targetRevision: HEAD
      ref: values

  destination:
    server: "https://kubernetes.default.svc"
    namespace: prometheus
