apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webcolor
  namespace: argocd
  labels:
    course: gitops
spec:
  project: default
  source:
    repoURL: "https://github.com/guilhermefaleiros/argocd.git"
    path: k8s
    targetRevision: HEAD
    directory:
      recurse: true
      exclude: "nginx/*"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: webcolor
  info:
    - name: Project
      value: "ArgoCD Lab"
